NAME: 'ssl_v8_vit_b_dinov2_resizev2.colorjitter.apl.adamw.mldecoder'

DATASET:
  TYPE: 'pedes'
  NAME: 'PPAR'
  TRAIN_SPLIT: 'train'
  VAL_SPLIT: 'val'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 224
  WIDTH: 224
  PATH: 'data/PPAR/dataset_all_20230913_batch8_full.pkl'

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:

#  TYPE: 'vit_b_path'
#  TYPE: 'vit_b_dinov1'
 TYPE: 'vit_b'

CLASSIFIER:
  # NAME: 'linear_vtb'
  NAME: 'mldecoder'
  # NAME: 'q2l'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'aplloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  USE_LABEL_EMBEDDING: False
  USE_VTB: False
  CLIP_GRAD: True
  BATCH_SIZE: 64
  MAX_EPOCH: 100
  OPTIMIZER:
    TYPE: 'adamw'
    WEIGHT_DECAY: 1e-4
  LR_SCHEDULER:
    TYPE: 'annealing_cosine'
    LR_FT: 0.0001
    LR_NEW: 0.0001
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
