NAME: 'batch8.20231025.box.256pad.{}.{}.emb{}.vtb{}.bs{}.{}e.{}.{}.{}.lrft{}.lrnew{}'

DATASET:
  TYPE: 'pedes'
  NAME: 'PPAR'
  TRAIN_SPLIT: 'train'
  VAL_SPLIT: 'val'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 256
  PATH: 'data/PPAR/dataset_v8_smoke_helmet_peseudo_20231109.pkl'

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  # TYPE: 'seresnet152d.ra2_in1k'
  # TYPE: 'resnet152d.ra2_in1k'
#  TYPE: 'bninception'
#  TYPE: 'tresnetM'
#  TYPE: 'swin_b'
 TYPE: 'swin_t_solider'
#  TYPE: 'vit_s'
#  TYPE: 'vit_b'
  # TYPE: 'convnext_b'
  # TYPE: 'swinv2_base_window8_256.ms_in1k'

CLASSIFIER:
  # NAME: 'linear'
  NAME: 'mldecoder'
  QRATIO: 1
  LRATIO: 1
  # NAME: 'q2l'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'aplloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  USE_LABEL_EMBEDDING: False
  USE_VTB: False # ViT only
  CLIP_GRAD: True
  BATCH_SIZE: 32
  MAX_EPOCH: 80
  OPTIMIZER:
    TYPE: 'adamw'
    WEIGHT_DECAY: 1e-4
  LR_SCHEDULER:
    TYPE: 'annealing_cosine'
    LR_FT: 0.00002
    LR_NEW: 0.00002
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
