DATA:
  IMG_ON_MEMORY: True
MODEL:
  TYPE: intern_image
  DROP_PATH_RATE: 0.5
  INTERN_IMAGE:
    CORE_OP: 'DCNv3'
    DEPTHS: [4, 4, 18, 4]
    GROUPS: [4, 8, 16, 32]
    CHANNELS: 64
    LAYER_SCALE: null
    OFFSET_SCALE: 1.0
    MLP_RATIO: 4.0
    POST_NORM: False
    RES_POST_NORM: False
    DW_KERNEL_SIZE: null
    USE_CLIP_PROJECTOR: False
    LEVEL2_POST_NORM: False
    LEVEL2_POST_NORM_BLOCK_IDS: null
    CENTER_FEATURE_SCALE: False
    REMOVE_CENTER: False
TRAIN:
  EMA:
    ENABLE: True
    DECAY: 0.9999
  USE_CHECKPOINT: False
  BASE_LR: 5e-4